---
  - name: Set ftpd_anon_write flag on and keep it persistent across reboots
    ansible.posix.seboolean:
      name: ftpd_anon_write
      state: yes
      persistent: yes
  - name: Allow full read/write access through SELinux
    seboolean:
      name: ftpd_full_access
      state: yes
      persistent: yes
    tags: vsftpd
    when:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version >= "7"
  - name: manage selinux settings
    sefcontext:
      target: "{{ pub_dir }}"
      setype: public_content_rw_t
      state: present
    notify:
      - run restorecon
...